print('Hello'
# The bug is in line 1. But the traceback appears at line 3.
print('How are you?')
